[project]
name = "uvinion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai>=1.1.0",
    "crewai-tools[mcp]>=1.1.0",
    "flask>=3.1.2",
    "mcp>=1.18.0",
]
